#' Emoticon count
#'
#' Count the number of emoticons in a string value
#' @param x A string value
#' @keywords text
#' @return vals The count of emoticons in a string
#' @export
#' @examples 
#' find_emoticon("I added some emoticons =] :D")
#' @seealso http://cool-smileys.com/text-emoticons

find_emoticon<-function(x){
    vec<-unlist(strsplit(x, " "))

    val1<-which(vec==":‑)")
    val2<-which(vec==":)")  
    val3<-which(vec==":-]")
    val4<-which(vec==":]")
    val5<-which(vec==":-3")
    val6<-which(vec==":3")   
    val7<-which(vec==":->")
    val8<-which(vec==":>")  
    val9<-which(vec=="8-)")
    val10<-which(vec=="8)")   
    val11<-which(vec==":-}")
    val12<-which(vec==":}")   
    val13<-which(vec==":o)")     
    val14<-which(vec==":c)")   
    val15<-which(vec==":^)")   
    val16<-which(vec=="=]" ) 
    val17<-which(vec=="=)" ) 
    val18<-which(vec==":‑D")
    val19<-which(vec==":D")  
    val20<-which(vec=="8‑D")
    val21<-which(vec=="8D")  
    val22<-which(vec=="x‑D")
    val23<-which(vec=="xD") 
    val24<-which(vec=="X‑D")
    val25<-which(vec=="XD")  
    val26<-which(vec=="=D")  
    val27<-which(vec=="=3")  
    val28<-which(vec=="B^D")     
    val29<-which(vec==":-))")      
    val30<-which(vec==":‑(")
    val31<-which(vec==":(")   
    val32<-which(vec==":‑c")
    val33<-which(vec==":c")   
    val34<-which(vec==":‑<")
    val35<-which(vec==":<")   
    val36<-which(vec==":‑[")
    val37<-which(vec==":[")  
    val38<-which(vec==":-||")    
    val39<-which(vec==">:[") 
    val40<-which(vec==":{")  
    val41<-which(vec==":@")  
    val42<-which(vec==">:(")    
    val43<-which(vec==":'‑(")
    val44<-which(vec==":'(") 
    val45<-which(vec==":'‑)")
    val46<-which(vec==":')")
    val47<-which(vec=="D‑':")    
    val48<-which(vec=="D:<") 
    val49<-which(vec=="D:")  
    val50<-which(vec=="D8")  
    val51<-which(vec=="D;")  
    val52<-which(vec=="D=")  
    val53<-which(vec=="DX")      
    val54<-which(vec==":‑O")
    val55<-which(vec==":O")   
    val56<-which(vec==":‑o")
    val57<-which(vec==":o")   
    val58<-which(vec==":-0")    
    val59<-which(vec=="8‑0") 
    val60<-which(vec==">:O")     
    val61<-which(vec==":-*")
    val62<-which(vec==":*")  
    val63<-which(vec==":×")     
    val64<-which(vec==";‑)")
    val65<-which(vec==";)")  
    val66<-which(vec=="*-)")
    val67<-which(vec=="*)")   
    val68<-which(vec==";‑]")
    val69<-which(vec==";]")  
    val70<-which(vec==";^)")     
    val71<-which(vec==":‑,")    
    val72<-which(vec==";D")     
    val73<-which(vec==":‑P")
    val74<-which(vec==":P")  
    val75<-which(vec=="X‑P")
    val76<-which(vec=="XP")  
    val77<-which(vec=="x‑p")
    val78<-which(vec=="xp")   
    val79<-which(vec==":‑p")
    val80<-which(vec==":p")   
    val81<-which(vec==":‑Þ")
    val82<-which(vec==":Þ")  
    val83<-which(vec==":‑þ")
    val84<-which(vec==":þ")   
    val85<-which(vec==":‑b")
    val86<-which(vec==":b")  
    val87<-which(vec=="d:")  
    val88<-which(vec=="=p")  
    val89<-which(vec==">:P")     
    val90<-which(vec==":‑/")
    val91<-which(vec==":/")   
    val92<-which(vec==":‑.")    
    #val93<-which(vec==">:\\") 
    val94<-which(vec==">:/")  
    #val95<-which(vec==":\\") 
    val96<-which(vec=="=/")  
    #val97<-which(vec=="=\\")   
    val98<-which(vec==":L") 
    val99<-which(vec=="=L")   
    val100<-which(vec==":S")     
    val101<-which(vec==":‑|")
    val102<-which(vec==":|")      
    val103<-which(vec==":$")    
    val104<-which(vec==":‑X")
    val105<-which(vec==":X")   
    val106<-which(vec==":‑#")
    val107<-which(vec==":#")   
    val108<-which(vec==":‑&")
    val109<-which(vec==":&")     
    val110<-which(vec=="O:‑)")
    val111<-which(vec=="O:)") 
    val112<-which(vec=="0:‑3")
    val113<-which(vec=="0:3") 
    val114<-which(vec=="0:‑)")
    val115<-which(vec=="0:)") 
    val116<-which(vec=="0;^)")       
    val117<-which(vec==">:‑)")
    val118<-which(vec==">:)") 
    val119<-which(vec=="}:‑)")
    val120<-which(vec=="}:)") 
    val121<-which(vec=="3:‑)")
    val122<-which(vec=="3:)") 
    val123<-which(vec==">;)")    
    val124<-which(vec=="|;‑)")   
    val125<-which(vec==":‑J")    
    val126<-which(vec=="%‑)")
    val127<-which(vec=="%)")  
    val128<-which(vec=="<:‑|")

    vals<-length(unique(c(val1,
                    val2,
                    val3,
                    val4,
                    val5,
                    val6,
                    val7,
                    val8,
                    val9,
                    val10,  
                    val11,
                    val12,
                    val13,
                    val14,
                    val15,
                    val16,
                    val17,
                    val18,
                    val19,
                    val20,
                    val21,
                    val22,
                    val23,
                    val24,
                    val25,
                    val26,
                    val27,
                    val28,
                    val29,
                    val30,
                    val31,
                    val32,
                    val33,
                    val34,
                    val35,
                    val36,
                    val37,
                    val38,
                    val39,
                    val40,
                    val41,
                    val42, 
                    val43,
                    val44,
                    val45,
                    val46,
                    val47,
                    val48,
                    val49,  
                    val50,
                    val51,
                    val52,
                    val53,
                    val54,
                    val55,
                    val56,
                    val57,  
                    val58,    
                    val59,
                    val60, 
                    val61,
                    val62,
                    val63,
                    val64,
                    val65,
                    val66,
                    val67,
                    val68,
                    val69,
                    val70, 
                    val71,
                    val72,
                    val73,
                    val74,
                    val75,
                    val76,
                    val77,
                    val78,
                    val79,
                    val80,
                    val81,
                    val82,
                    val83,
                    val84,
                    val85,
                    val86,
                    val87,
                    val88,
                    val89,
                    val90,
                    val91,
                    val92,
#                    val93,
                    val94,
#                    val95, 
                    val96,
#                    val97,
                    val98,
                    val99,  
                    val100,    
                    val101,
                    val102,     
                    val103,
                    val104,
                    val105,
                    val106,
                    val107,
                    val108,
                    val109, 
                    val110,
                    val111,
                    val112,
                    val113,
                    val114,
                    val115,
                    val116,    
                    val117,
                    val118,
                    val119,
                    val120,
                    val122,
                    val123,
                    val124,
                    val125,
                    val126,
                    val127,
                    val128)))
    return(vals)
}